### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by alair069** [Muqsit/FakeBlood#1]
[Tesseract] [17:05:47] CRITICAL> ParseError: "syntax error, unexpected 'EntityDamageByEntityEvent' (T_STRING)" (EXCEPTION) in "/plugins/FakeBlood-master/src/Muqsit/FakeBlood" at line 19
[Tesseract] [17:05:47] EMERGENCY> An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by iPeedroPvP** [comment]
remove EntityDamageByEntityEvent of user class.
